<?php
// Only allow access to this dashboard if there's a valid LTI context and the student is in the research group
if ( $context->valid && isset($_SESSION["group"]) &&  $_SESSION["group"] == "research" ) {
?>

<!-- Welcome jumbotron message -->
<div class="jumbotron hidden" id="welcomeJumbotron">
  <h1>Welcome!</h1>
  <p>This dashboard will display recommendations to you about which videos and quizzes should be reviewed, based on your online activity.</p>
  <p><button class="btn btn-primary btn-large" data-dismiss="welcomeJumbotron" id="jumbotronDismiss">Continue to Dashboard</button></p>
</div>

<!-- Container for concepts, recommendations, and advanced -->
<div id="mainContainer" class="container hidden">
  <div class="row">

    <!-- Filter Navigation -->
    <div id="filterSection" class="col-sm-12">
      <p class="lead">Click on a concept to see recommendations on how to improve your mastery score.</p>
      <div id="filterLoadingContainer">
		<h3 class="capsLabel" style="display: inline; padding-left: 0px;">See concepts from unit: </h3>
	    <label for="filterUnitSelector">&nbsp;</label><select class="unitSelector" name="filterUnitSelector">
	      <?php foreach ($units as $unit) { echo '<option value="'.$unit['id'].'">'.$unit['title'].'</option>'; } ?>
	    </select>
  	    <div id="filterList">
          <span class="" id="conceptListHeader"><hr><div style="margin: 15px 0px 0px 80px;">Concept name </div><div style="margin-top: -20px;" class="filterListItemScore">Your mastery score</div><hr></span>
          <!--<a class="filterListUnit"><div class="filterListItemText">&nbsp;&nbsp;&nbsp;&nbsp; View recommendations for all concepts in Unit <span id="filterListUnitName"></span></div></a>-->
        </div>
      </div>
      <span class="spinner"><br /><?php echo Phalcon\Tag::image("img/spinner.gif"); ?><br /></span>
    </div>
  </div>
</div>
<div class="col-sm-9"><div class="row">
  <!-- Recommendations -->
  <div id="recommendSection" class="hidden">
    <div class="col-sm-12">
      <div class="row">
        <div class="col-sm-4 col-md-4 col-lg-4">
          <h1>Practice Quiz</h1>
          <br>
          <td><a role="button" class="btn btn-info btn-large" id="quiz-launch"><span class="glyphicon glyphicon-log-in"></span> &nbsp; Launch Quiz &nbsp;</a></td>
        </div>
        <div class="col-sm-4 col-md-4 col-lg-4">
          <h1>Class Videos</h1>
          <div>
            <table class="table" id="recommendVideosTable">
              <span class="spinner"><br /><?php echo Phalcon\Tag::image("img/spinner.gif"); ?><br /></span>
    					<thead><tr><th>Video Name</th><th class="videoProgressCell">&nbsp;% Watched</th></tr></thead>
    					<tbody></tbody>
    				</table>
          </div>
        </div>
        <div class="col-sm-4 col-md-4 col-lg-4">
          <h1>Web Resources</h1>
          <div>
            <table class="table" id="relatedResourcesTable">
    					<thead><tr><th>Resource Name</th></tr></thead>
    					<tbody></tbody>
    				</table>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</div>

<!-- Quiz launch modal dialog -->
<div class="modal fade" tabindex="-1" id="questionLaunchModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">This quiz has not been published.</h4>
			</div>
			<div class="modal-body">
				Look back later to check if it has been published.  Until then, check out some of the other resources.
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
				<!-- <a href="#" target="_blank" id="questionLaunchContinueButton" type="button" class="btn btn-primary">Continue to practice</a> -->
			</div>
		</div>
	</div>
</div>

<!-- Related videos modal dialog -->
<div class="modal fade" tabindex="-1" id="relatedVideosModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Videos related to this concept</h4>
			</div>
			<div class="modal-body">
				<table class="table" id="relatedVideosModalTable">
					<thead><tr><th>Video Name</th><!--<th class="advancedMore">% Watched</th>--></tr></thead>
					<tbody></tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<!-- Feedback modal dialog -->
<div class="modal fade" tabindex="-1" id="feedbackModal">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Send Feedback</h4>
			</div>
			<div class="modal-body">
              <form action="javascript:void(0);" id="feedbackForm">
                <select class="form-control" id="feedbackTypeSelector">
                  <option value="problem">Report an issue</option>
                  <option value="suggestion">Give a suggestion</option>
                </select>
                <div class="alert alert-danger hidden" id="feedbackEmptyAlert">Enter your feedback here:</div>
                <textarea class="form-control lead" rows="3" id="feedbackTextArea" placeholder="Have a suggestion? Found an issue? Send us your feedback."></textarea>
                <button type="submit" class="btn btn-default btn-block" id="feedbackSendButton">Send Feedback</button>
              </form>
	          <p class="lead hidden" id="feedbackResult"></p>
              <span class="spinner hidden" id="feedbackSpinner"><?php echo Phalcon\Tag::image("img/spinner.gif"); ?></span>
			</div>
		</div>
	</div>
</div>

<?php
echo Phalcon\Tag::javascriptInclude("js/vendor/jquery.knob.min.js");
echo Phalcon\Tag::javascriptInclude("js/vendor/jquery.stickytableheaders.min.js");
echo Phalcon\Tag::javascriptInclude("js/vendor/jquery.shorten.js");
echo Phalcon\Tag::javascriptInclude("js/content_recommender.js");
echo Phalcon\Tag::stylesheetLink("css/content_recommender.css");

} else {
	echo "<p class='alert alert-danger'>Not logged in, or there was an LTI error. Try launching this app again.</p>";
}
