<?php
if ( $context->valid ) {
?>

<!-- Welcome jumbotron message -->
<div class="jumbotron" id="welcomeJumbotron">
  <h1>Welcome!</h1>
  <p>This dashboard will display recommendations to you about which videos and quizzes should be reviewed, based on your online activity.</p>
  <p><button class="btn btn-primary btn-large" data-dismiss="welcomeJumbotron" id="jumbotronDismiss">Continue to Dashboard</button></p>
</div>

<!-- Container for concepts, recommendations, and advanced -->
<div id="mainContainer" class="container hidden">
  <div class="row">
    <div class="col-sm-9"><div class="row">

      <!-- Concepts -->
      <div id="conceptsSection" class="advancedSimple advancedAll col-md-12">
        <div class="row">
	  <div class="col-sm-6">
            <h3>Strongest Concepts</h3>
            <span class="spinner"><?php echo Phalcon\Tag::image("img/spinner.gif"); ?><br /></span>
              <div class="conceptsList" id="strongestConceptsList"> </div>
          </div>
	  <div class="col-sm-6">
            <h3>Weakest Concepts</h3>
            <span class="spinner"><?php echo Phalcon\Tag::image("img/spinner.gif"); ?><br /></span>
              <div class="conceptsList" id="weakestConceptsList"> </div>
          </div>
        </div>
        <div class="row"><hr><br></div>
      </div>
  
      <!-- Recommendations -->
      <div id="recommendSection" class="advancedSimple advancedAll col-md-12">
          <h3 style="float: left;">Question Recommendations</h3>

		  <div class="pull-right">
          <h3 style="display: inline;"><small><i>Filter recommendations by: </i></small></h3>
            <form>
              <div class="btn-group" style="float: left;" data-toggle="buttons">
  				<label class="btn btn-default scopeOptionLabel"><input type="radio" name="recommendScopeOption" id="recommendConceptButton" value="concept"/>Concept: 
  						<select class="conceptSelector" id="recommendConceptSelector" name="recommendConceptSelector">
  						  <?php foreach ($concepts as $concept) { echo '<option value="'.$concept['id'].'">'.$concept['title'].'</option>'; } ?>
  						</select>
  					  </label>
  				<label class="btn btn-default scopeOptionLabel"><input type="radio" name="recommendScopeOption" value="chapter" />Chapter: 
  						<select class="chapterSelector" name="recommendChapterSelector">
  						  <?php foreach ($chapters as $chapter) { echo '<option value="'.$chapter['id'].'">'.$chapter['title'].'</option>'; } ?>
  						</select>
  					  </label>
  				<label class="btn btn-default scopeOptionLabel active"><input type="radio" name="recommendScopeOption" value="unit" checked />Unit: 
  						<select class="unitSelector" name="recommendUnitSelector">
  						  <?php foreach ($units as $unit) { echo '<option value="'.$unit['id'].'"'; if ($unit['id']==3) { echo ' selected="selected"'; } echo '>'.$unit['title'].'</option>'; } ?>
  						</select>
  					  </label>
              </div>
            </form>
		    <span class="spinner" style="float: right;"><br /><?php echo Phalcon\Tag::image("img/spinner.gif"); ?><br /></span>
          </div><br>

          <ul class="nav nav-tabs" style="clear: both;" id="recommendTabs" role="tablist">
			<li role="presentation" class="active"><a href="#recommend1" aria-controls="recommend1" role="tab" data-toggle="tab"><div class="text-center">Attempt these questions <span class="countBadge"></span></div></a></li>
			<li role="presentation"><a href="#recommend2" aria-controls="recommend2" role="tab" data-toggle="tab"><div class="text-center">Watch these videos <span class="countBadge"></span></div></a></li>
			<li role="presentation"><a href="#recommend3" aria-controls="recommend3" role="tab" data-toggle="tab"><div class="text-center">Find additional help <span class="countBadge"></span></div></a></li>
			<li role="presentation"><a href="#recommend4" aria-controls="recommend4" role="tab" data-toggle="tab"><div class="text-center">Practice these again <span class="countBadge"></span></div></a></li>
          </ul>

          <div class="tab-content">
            <!-- Group 1 -->
             <div role="tabpanel" class="tab-pane active" id="recommend1">
                <div class="recommendInfo alert alert-info" id="recommend1Info"><span class="glyphicon glyphicon-info-sign"></span><h4>You did not attempt these questions</h4> <p>These questions were selected because you have not attempted them yet. This material will likely be on an upcoming exam, so to improve your score, it is recommended that you practice these questions.</p></div>
                <table class="table table-hover table-striped sticky-header" id="recommend1List"> </table>
              </div>

            <!-- Group 2 -->
             <div role="tabpanel" class="tab-pane" id="recommend2">
  	            <div class="recommendInfo alert alert-info" id="recommend2Info"><span class="glyphicon glyphicon-info-sign"></span><h4>You did not watch the videos for these questions</h4> <p>These questions were selected because, based on your online activity, it seems you did not watch the videos before you attempted the quiz. To better learn the material, it is recommended that you watch the videos associated with these quiz questions.</p></div>
                <table class="table table-hover table-striped sticky-header" id="recommend2List"> </table>
              </div>

            <!-- Group 3 -->
             <div role="tabpanel" class="tab-pane" id="recommend3">
  	            <div class="recommendInfo alert alert-info" id="recommend3Info"><span class="glyphicon glyphicon-info-sign"></span><h4>You tried but did not succeed</h4> <p>These questions were selected because you have spent time watching the videos, but for some reason, the quiz was still difficult for you. To learn this material, you may want to email the instructor, go into the TA lab, or ask a friend to help you.</p></div>
                <table class="table table-hover table-striped sticky-header" id="recommend3List"> </table>
              </div>

            <!-- Group 4 -->
             <div role="tabpanel" class="tab-pane" id="recommend4">
  	            <div class="recommendInfo alert alert-info" id="recommend4Info"><span class="glyphicon glyphicon-info-sign"></span><h4>You eventually got it right</h4> <p>These questions were selected because even though you eventually answered it correctly, you missed them multiple times at first. These questions are recommended you to re-do to help you solidify your understanding.</p></div>
				<table class="table table-hover table-striped sticky-header" id="recommend4List"> </table>
              </div>

            </div>

      </div>
  
     
      
      <div id="templates" class="hidden">
        <table id="recommendTemplates">
        <!-- Template for recommendation table header -->
        <thead class="recommendHeaderTemplate">
          <tr class="advancedMoreClass">
            <th colspan="3"></th>
            <th colspan="3" style="border-left: 2px solid #ddd; border-right: 2px solid #ddd;"><span class="advancedMoreClass">Class</span></th>
            <th colspan="2"></th>
          </tr>
          <tr>
            <th>Quiz Question</th>
            <th style="text-align: center;"><span class="advancedMore">Correct</span></th>
            <th style="text-align: center;"><span class="advancedMore">Attempts</span></th>
            <th><span class="advancedMoreClass">Viewed<br>Hint</span></th>
            <th><span class="advancedMoreClass">Viewed<br>Answer</span></th>
            <th><span class="advancedMoreClass">Average<br>Attempts</span></th>
            <th><!--Launch Quiz--></th>
            <th><!--See Related Videos--></th>
          </tr>
        </thead>
        <!-- Template for recommendation item -->
        <tr class="recommendQuestionDisplay">
  	  <td><span class="recommendQuestionTextContainer">{display}</span></td>
	  <td style="text-align: center;"><span class="advancedMore correct-{correct}Holder"><span class="glyphicon glyphicon-ok correctIcon"></span><span class="glyphicon glyphicon-remove incorrectIcon"></span></span></td>
	  <td style="text-align: center;"><span class="advancedMore" style="font-weight: bold;">{attempts}</span></td>
          <td><span class="advancedMoreClass">{classViewedHint}%</span></td>
          <td><span class="advancedMoreClass">{classViewedAnswer}%</span></td>
          <td><span class="advancedMoreClass">{classAverageAttempts}</span></td>
          <td><button class="btn btn-info btn-xs" data-toggle="modal" data-target="#questionLaunchModal" data-assessment="{assessmentId}" data-question="{questionNumber}"> <span class="glyphicon glyphicon-log-in"></span> &nbsp; Quiz &nbsp;</button></td>
  	  <td><button class="btn btn-info btn-xs" data-toggle="modal" data-target="#relatedVideosModal" data-assessment="{assessmentId}" data-question="{questionNumber}"> <span class="glyphicon glyphicon-film"></span> &nbsp; Videos &nbsp;</button></td>
        </tr>
        </table>
      </div>
      
      <!-- Scatterplot -->
      <div id="scatterplotSection" class="advancedScatterplot col-md-12">
        <h3>Question Scatterplot</h3>
          <span class="spinner pull-right"><?php echo Phalcon\Tag::image("img/spinner.gif"); ?><br /></span>
          <form>
            <div class="btn-group" data-toggle="buttons">
  	    <label class="btn btn-default active scopeOptionLabel"><input type="radio" name="scatterplotScopeOption" value="concept" checked />Concept: 
                <select class="conceptSelector" name="scatterplotConceptSelector">
                  <?php foreach ($concepts as $concept) { echo '<option value="'.$concept['id'].'">'.$concept['title'].'</option>'; } ?>
                </select>
              </label>
  	    <label class="btn btn-default scopeOptionLabel"><input type="radio" name="scatterplotScopeOption" value="chapter" />Chapter: 
                <select class="chapterSelector" name="scatterplotChapterSelector">
                  <?php foreach ($chapters as $chapter) { echo '<option value="'.$chapter['id'].'">'.$chapter['title'].'</option>'; } ?>
                </select>
              </label>
  	    <label class="btn btn-default scopeOptionLabel"><input type="radio" name="scatterplotScopeOption" value="unit" />Unit: 
                <select class="unitSelector" name="scatterplotUnitSelector">
                  <?php foreach ($units as $unit) { echo '<option value="'.$unit['id'].'">'.$unit['title'].'</option>'; } ?>
                </select>
              </label>
            </div>
          </form>
	  <div id="quadrantInfo1" class="quadrantInfo hidden">
	    <p class="lead">
              Quadrant 1 info
	    </p>
          </div>
	  <div id="quadrantInfo2" class="quadrantInfo hidden">
	    <p class="lead">
              Quadrant 2 info
	    </p>
          </div>
	  <div id="quadrantInfo3" class="quadrantInfo hidden">
	    <p class="lead">
              Quadrant 3 info
	    </p>
          </div>
	  <div id="quadrantInfo4" class="quadrantInfo hidden">
	    <p class="lead">
              Quadrant 4 info
	    </p>
          </div>
      </div>
  
      <!-- Concept Mastery Graph -->
      <div id="masteryGraphSection" class="advancedMasteryGraph col-md-12">
        <h3>All Concept Mastery Scores<small></small></h3>
          <span class="spinner pull-right"><?php echo Phalcon\Tag::image("img/spinner.gif"); ?><br /></span>
          <form>
            <div class="btn-group" data-toggle="buttons">
  	    <label class="btn btn-default scopeOptionLabel"><input type="radio" name="masteryGraphScopeOption" value="chapter" />Chapter: 
                <select class="chapterSelector" name="masteryGraphChapterSelector">
                  <?php foreach ($chapters as $chapter) { echo '<option value="'.$chapter['id'].'">'.$chapter['title'].'</option>'; } ?>
                </select>
              </label>
  	    <label class="btn btn-default scopeOptionLabel active"><input type="radio" name="masteryGraphScopeOption" value="unit" checked />Unit: 
                <select class="unitSelector" name="masteryGraphUnitSelector">
                  <?php foreach ($units as $unit) { echo '<option value="'.$unit['id'].'"'; if ($unit['id']==3) { echo ' selected="selected"'; } echo '>'.$unit['title'].'</option>'; } ?>
                </select>
              </label>
              <!--<label class="btn btn-default scopeOptionLabel"><input type="radio" name="masteryGraphScopeOption" value="all" />All</label>-->
            </div>
          </form><br><br>
  	<div class="svgContainer"></div>
      </div>

    </div></div>

    <!-- Advanced -->
    <div id="advancedSection" class="col-sm-3">
      <!-- Figure out a better way to have advanced bar sticky, but still responsive <div class="affix" style="width: 90%;"> -->
        <h3>Advanced</h3>
        <ul class="nav nav-pills nav-stacked">
	      <li role="presentation" class="advancedToggleLi active">
	        <a id="advancedToggleSimple" class="advancedToggle" data-option="simple" href="#">See recommendations</a>
	        <div class="advancedToggleOptional"><input id="advancedToggleMore" class="advancedToggleOptional" data-option="more" type="checkbox" />&nbsp;<label for="advancedToggleMore">See more details</label><br></div>
	        <div class="advancedToggleOptional"><input id="advancedToggleMoreClass" disabled class="advancedToggleOptional" data-option="moreClass" type="checkbox" />&nbsp;<label for="advancedToggleMoreClass">Compare to class</label></div>
          </li>
          <!-- <li role="presentation" class="advancedToggleLi"><a id="advancedToggleScatterplot" class="advancedToggle" data-option="scatterplot" href="#">See scatterplot for these concepts</a><div class="advancedToggleOptional"><input id="advancedToggleScatterplotClass" class="advancedToggleOptional" data-option="scatterplotClass" type="checkbox" />&nbsp;<label for="advancedToggleScatterplotClass">Compare to class</label></div></li> -->
	      <li role="presentation" class="advancedToggleLi">
	        <a id="advancedToggleMasteryGraph" class="advancedToggle" data-option="masteryGraph" href="#">See all concept scores</a>
	        <!-- <div class="advancedToggleOptional"><input id="advancedToggleMore" class="advancedToggleOptional" data-option="more" type="checkbox" />&nbsp;<label for="advancedToggleMore">See more details</label></div> -->
          </li>
        </ul>
        <h3>Feedback</h3>
        <form action="javascript:void(0);" id="feedbackForm">
          <select class="form-control" id="feedbackTypeSelector">
            <option value="problem">Report an issue</option>
            <option value="suggestion">Give a suggestion</option>
          </select>
          <div class="alert alert-danger hidden" id="feedbackEmptyAlert">Enter your feedback here:</div>
          <textarea class="form-control lead" rows="3" id="feedbackTextArea" placeholder="Have a suggestion? Found an issue? Send us your feedback."></textarea>
          <button type="submit" class="btn btn-default btn-block" id="feedbackSendButton">Send Feedback</button>
        </form>
        <span class="spinner hidden" id="feedbackSpinner"><?php echo Phalcon\Tag::image("img/spinner.gif"); ?></span>
	    <p class="lead" id="feedbackResult"></p>
      <!--<div>-->
    </div>

  </div>
</div>

<!-- Quiz launch modal dialog -->
<div class="modal fade" tabindex="-1" id="questionLaunchModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">This quiz is for practice only.</h4>
			</div>
			<div class="modal-body">
				To have this quiz count for your grade, launch this quiz through Learning Suite.
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Do not launch</button>
				<a href="#" target="_blank" id="questionLaunchContinueButton" type="button" class="btn btn-primary">Continue to practice</a>
			</div>
		</div>
	</div>
</div>

<!-- Related videos modal dialog -->
<div class="modal fade" tabindex="-1" id="relatedVideosModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Videos related to this question</h4>
			</div>
			<div class="modal-body">
				<table class="table" id="relatedVideosModalTable">
					<thead><tr><th>&nbsp;</th><th>Video Name</th><!--<th class="advancedMore">% Watched</th>--></tr></thead>
					<tbody></tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<!-- This is the existing content recommender stuff -->
<!-- Content tables -->
<div id="mainContainer" class="container hidden">
  <div class="row">
    <div id="questionsTable" class="col-md-6">
      <div class=""><h3>Quiz Questions <small>— Sorted by attempts</small></h3></div>
      <span class="spinner"><?php echo Phalcon\Tag::image("img/spinner.gif"); ?><br /></span>
      <table class="table table-striped table-hover">
      </table>
    </div>
    <div id="videosTable" class="col-md-6">
      <h3 class="">Videos <small>— Only showing required</small></h3>
      <table class="table table-striped table-hover">
        <colgroup><col><col><col class="colWatched"></colgroup>
        <thead><tr><th>&nbsp;</th><th>Video Name</th><th>% Watched</th></tr></thead>
	<tbody></tbody>
      </table>
      <span class="spinner"><?php echo Phalcon\Tag::image("img/spinner.gif"); ?><br /></span>
    </div>
  </div>
</div>


<?php
echo Phalcon\Tag::javascriptInclude("js/vendor/jquery.knob.min.js");
echo Phalcon\Tag::javascriptInclude("js/vendor/jquery.stickytableheaders.min.js");
echo Phalcon\Tag::javascriptInclude("js/vendor/jquery.shorten.js");
echo Phalcon\Tag::javascriptInclude("js/content_recommender.js");
echo Phalcon\Tag::stylesheetLink("css/content_recommender.css");

} else {
	echo "<p class='alert alert-danger'>Not logged in, or there was an LTI error. Try launching this app again.</p>";
}

