<h2>Content Recommender Dashboard</h2>
<?php
if ( $context->valid ) {
?>
<div id="visualizationContainer" class="container">
  <div class="row">
    <div id="questionsTable" class="col-md-6">
      <div class="center-block"><h3>Quiz Questions <small>— Sorted by attempts</small></h3></div>
      <span class="spinner"><?php echo Phalcon\Tag::image("img/spinner.svg"); ?><br /></span>
      <table class="table table-striped table-hover">
      </table>
    </div>
    <div id="videosTable" class="col-md-6">
      <h3 class="center-block">Videos <small>— Only showing required</small></h3>
      <table class="table table-striped table-hover">
        <colgroup><col><col><col class="colWatched"></colgroup>
        <thead><tr><th>&nbsp;</th><th>Video Name</th><th>% Watched</th></tr></thead>
	<tbody></tbody>
      </table>
      <span class="spinner"><?php echo Phalcon\Tag::image("img/spinner.svg"); ?><br /></span>
    </div>
  </div>
</div>

<!-- <div class="visualization" id="openAssessmentStats" style="width: 450px; height: 390px;">
	<h3>Open Assessments User Statistics</h3>
	<span class="spinner"><?php echo Phalcon\Tag::image("img/spinner.svg"); ?><br /></span>
	<svg width="0" height="0">
	</svg>
</div>
<div class="modal fade" tabindex="-1" id="openAssessmentStatsModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Dialog Title</h4>
			</div>
			<div class="modal-body">
				Load more related content here
			</div>
		</div>
	</div>
</div>

</div>
-->

<?php
echo Phalcon\Tag::javascriptInclude("js/vendor/jquery.knob.min.js");
echo Phalcon\Tag::javascriptInclude("js/content_recommender.js");
echo Phalcon\Tag::stylesheetLink("css/content_recommender.css");

} else {
	echo "<p class='bg-danger'>Not logged in, or there was an LTI error. Try launching this app again.</p>";
}

