<h2>Visualization Dashboard</h2>
<?php
if ( $context->valid ) {
?>
<div id="visualizationContainer">

<div class="visualization" id="openAssessmentStats" style="width: 450px; height: 390px;">
	<h3>Open Assessments User Statistics</h3>
	<span class="spinner"><?php echo Phalcon\Tag::image(array("img/spinner.svg", "alt" => "Loading...")); ?><br /></span>
	<svg width="0" height="0">
	</svg>
</div>

<div class="visualization" id="ayamelStats" style="width: 650px; height: 405px;">
	<h3>Ayamel Global Verb Counts<br /><small>Only verbs with >3% of statements included</small></h3>
	<span class="spinner"><?php echo Phalcon\Tag::image(array("img/spinner.svg", "alt" => "Loading...")); ?><br /></span>
	<svg width="0" height="0">
	</svg>
</div>

<div class="visualization" id="confidencePie" style="width: 620px; height: 550px;">
	<h3>User Answer Confidence</h3>
	<span class="spinner"><?php echo Phalcon\Tag::image(array("img/spinner.svg", "alt" => "Loading...")); ?><br /></span>
	<div id="confidencePieContainer"></div>
</div>

<div class="visualization" id="circleFun">
	<h3>Circle transitions</h3>
	<input id="circleDataSize" type="range" min="0" max="20" value="5" />
	<label id="cirlceDataSizeLabel"></label>
	<svg width="100%" height="100">
	</svg>
</div>

<div class="visualization" id="barGraph">
	<h3>Basic Static Bar Graph</h3>
	<svg width="500" height="300">
	</svg>
</div>

</div>

<?php
} else {
	echo "Not logged in, or there was an LTI error. Try launching this app again.";
}
