<h2>Visualization Dashboard</h2>
<?php
if ( $context->valid ) {
?>

<div class="visualization" id="circleFun">
	<input id="dataSize" type="range" min="0" max="20" value="5" />
	<label id="dataSizeLabel"></label>
	<svg width="100%" height="100">
	</svg>
</div>

<div class="visualization" id="barGraph">

</div>

<?php
} else {
	echo "Not logged in, or there was an LTI error. Try launching this app again.";
}
