<?php
if ( $context->valid ) {
?>
<div class="container center">
	<div class="row">
		<h2>Course Resources</h2>
		<hr>
		<?php
		foreach ($concepts as $concept) {
			// Print title for each concept
			echo "<h3 name=\"{$concept['id']}\" id=\"concept{$concept['id']}\" data-concept=\"{$concept['id']}\">{$concept['title']}</h3>";
			$formattedDate = date('M j', strtotime($concept["date"]));
			
			// Make list for each concept
			echo '<ul class="list-group resource-list">';
			// Print each resource for this concept
			foreach ($resources[$concept["id"]] as $resource) {
				echo "<li class=\"list-group-item resource-{$resource["Resource Type"]}\">";
				if ($resource["Resource Type"] == "web") {
					echo '<span class="glyphicon glyphicon-globe" aria-hidden="true">&nbsp;</span>';
					echo "<a href=\"{$resource["Resource Link"]}\" data-track=\"concept{$resource["Lecture Number"]}Link{$resource["Resource Tracking Number"]}\" target=\"_blank\">{$resource["Resource Title"]}</a>";
				} else if ($resource["Resource Type"] == "ayamel") {
					echo '<span class="glyphicon glyphicon-film" aria-hidden="true">&nbsp;</span>';
					echo "<a href=\"../consumer.php?app=ayamel&video_id={$resource["Resource Link"]}\" data-track=\"concept{$resource["Lecture Number"]}Video{$resource["Resource Tracking Number"]}\" target=\"_blank\">{$resource["Resource Title"]}</a>";
				}
				echo "<span class=\"badge resource-date-badge\">{$formattedDate}</span>";
				echo '</li>';
			}
			echo '</ul>';
		}
		?>
	</div>
</div>

<script>
	$(function() {
		function track(verbName, objectName) {
			console.log("Tracking: ",verbName,objectName);
			sendStatement({
				statementName: 'interacted',
				dashboardID: 'resources_dashboard',
				dashboardName: 'Resources Dashboard',
				verbName: verbName,
				objectName: objectName
			});
		}
		// Set up event listener for links that we want to track
		$(document).on("click", "[data-track]", function() {
			track("clicked", $(this).attr("data-track"));
		});
		
		$("html, body").animate({ scrollTop: $('h3[data-concept="<?php echo $currentConceptID; ?>"]').offset().top - 65 }, "fast");
	});
</script>

<?php
} else {
	echo "<p class='alert alert-danger'>Not logged in, or there was an LTI error. Try launching this app again.</p>";
}
