<?php
if ( $context->valid ) {
?>
<div class="container center">
	<div class="row">
		<h2>Course Resources</h2>
		<hr>
		<?php
		foreach ($concepts as $concept) {
			echo "<h3 name=\"{$concept['id']}\" id=\"section{$concept['id']}\">{$concept['title']}</h3>";
		}
		?>
	</div>
</div>

<?php
} else {
	echo "<p class='alert alert-danger'>Not logged in, or there was an LTI error. Try launching this app again.</p>";
}
