<?php
if ( $context->valid ) {
?>

<!-- Welcome jumbotron message -->
<div class="jumbotron" id="welcomeJumbotron">
  <h1>Welcome!</h1>
  <p>This dashboard will display recommendations to you about which student skills should be improved on in order to become a better student based on your online activity.</p>
  <p><button class="btn btn-primary btn-large" data-dismiss="welcomeJumbotron" id="jumbotronDismiss">Continue to Dashboard</button></p>
</div>

<!-- Container for skills list, time chart, skills graph, and advanced -->
<div id="mainContainer" class="container">
  <div class="row">
    <div class="col-sm-9"><div class="row">

      <!-- Skills List Section -->
      <div id="skillsListSection" class="advancedSimple advancedAll col-md-12">
        <div class="row vertical-divider">
	  <div class="col-sm-6">
            <h3>Your Strongest Skill<span class="advancedAll">s</span></h3>
            <span class="spinner"><?php echo Phalcon\Tag::image("img/spinner.svg"); ?><br /></span>
              <div id="strongestSkillsList"> </div>
          </div>
	  <div class="col-sm-6">
            <h3>Your Weakest Skill<span class="advancedAll">s</span></h3>
            <span class="spinner"><?php echo Phalcon\Tag::image("img/spinner.svg"); ?><br /></span>
              <div id="weakestSkillsList"> </div>
          </div>
        </div>
      </div>

      <!-- Time Graph -->
      <div id="timeGraphSection" class="advancedTimeGraph col-md-12">
        <h3>Your Skills Over Time<small>— currently random numbers</small></h3>
        <div id="visualizationContainer" class="container">
            <div id="timeGraphContainer">
              <span class="spinner"><?php echo Phalcon\Tag::image("img/spinner.svg"); ?><br /></span>
              <div id="timeGraph"></div>
            </div>
            <h5>Select a skill:</h5>
            <form>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default active"><input type="radio" name="timeGraphSkillOption" value="time" checked />Time Management</label>
                <label class="btn btn-default"><input type="radio" name="timeGraphSkillOption" value="activity" />Online Activity</label>
                <label class="btn btn-default"><input type="radio" name="timeGraphSkillOption" value="regulation" />Self-Regulation</label>
                <label class="btn btn-default"><input type="radio" name="timeGraphSkillOption" value="efficacy" />Self-Efficacy</label>
                <label class="btn btn-default"><input type="radio" name="timeGraphSkillOption" value="consistency" />Consistency</label>
              </div>
            </form>
        </div>
      </div>

      <!-- Skills Graph -->
      <div id="skillsGraphSection" class="advancedSkillsGraph col-md-12">
        <h3>Student Skills<small>— currently random numbers</small></h3>
        <div id="visualizationContainer" class="container">
            <div id="radarContainer">
              <span class="spinner"><?php echo Phalcon\Tag::image("img/spinner.svg"); ?><br /></span>
              <div id="radarChart"></div>
            </div>
        </div>
      </div>
   
    </div></div>
      
    <!-- Advanced -->
    <div id="advancedSection" class="col-sm-3">
      <h3>Change View</h3>
      <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="advancedToggleLi active"><a id="advancedToggleSimple" class="advancedToggle" data-option="simple" href="#">See simple view</a></li>

	<li role="presentation" class="advancedToggleLi"><a id="advancedToggleAll" class="advancedToggle" data-option="all" href="#">See all skills</a>
	  <div class="advancedToggleOptional"><input id="advancedToggleAllScores" class="advancedToggleOptional" data-option="allScores" type="checkbox" />&nbsp;<label for="advancedToggleAllScores">Show skill scores</label><br /></div>
	  <div class="advancedToggleOptional"><input id="advancedToggleAllScoresClass" class="advancedToggleOptional" data-option="allScoresClass" type="checkbox" />&nbsp;<label for="advancedToggleAllScoresClass">Compare to class</label></div>
        </li>
        <li role="presentation" class="advancedToggleLi"><a id="advancedToggleTimeGraph" class="advancedToggle" data-option="timeGraph" href="#">See skills over time</a><div class="advancedToggleOptional"><input id="advancedToggleTimeGraphClass" class="advancedToggleOptional" data-option="timeGraphClass" type="checkbox" />&nbsp;<label for="advancedToggleTimeGraphClass">Compare to class</label></div></li>
        <li role="presentation" class="advancedToggleLi"><a id="advancedToggleSkillsGraph" class="advancedToggle" data-option="skillsGraph" href="#">See my skills graph</a></li>
      </ul>
    </div>
   
  </div>
</div>

<div id="templates" class="hidden">

  <div class="timeSkillTemplate skillTemplate">
    <div class="skillScoreBar">
      <h4>Time Management
      <span class="skillInfo pull-right" id="timeSkillInfo" data-toggle="tooltip" title="Time Management is planning ahead and working on your work well before the due date."><span class="glyphicon glyphicon-info-sign"></span></span>
      <span class="advancedAllScores pull-right">Your score: <span class="skillScoreLabel"></span>/10</span>
      <span class="advancedAllScoresClass skillPercentileHolder pull-right"><small>Your percentile in class: <span class="skillPercentileLabel"></span>%</small></span>
      </h4>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" data-score="0"><h5>To improve your Time Management skill, you should:</h5></div>
      <ol class="list-group">
        <li class="list-group-item">1. Try to complete your online work before 10pm the day before they are due</li>
        <li class="list-group-item">2. Plan ahead so you won't be bogged down by multiple projects</li>
        <li class="list-group-item">3. Visit these online resources to learn about time management and procrastination: <br>
          <ol><li class="list-group-item">
	    <a href="https://www.youtube.com/watch?v=Qvcx7Y4caQE" target="_blank" data-toggle="tooltip" title="How to Stop Procrastinating"><?php echo Phalcon\Tag::image("img/videoTime1.png"); ?></a>
            <a href="https://www.youtube.com/watch?v=VUk6LXRZMMk" target="_blank" data-toggle="tooltip" title="How to Manage Your Time Better"><?php echo Phalcon\Tag::image("img/videoTime2.png"); ?></a>
          </li></ol>
        </li>
      </ul>
    </div>
  </div>

  <div class="activitySkillTemplate skillTemplate">
    <div class="skillScoreBar">
      <h4>Online Activity
      <span class="skillInfo pull-right" id="activitySkillInfo" data-toggle="tooltip" title="Online activity is how much you interact with the online videos and quizzes."><span class="glyphicon glyphicon-info-sign"></span></span>
      <span class="advancedAllScores pull-right">Your score: <span class="skillScoreLabel"></span>/10</span>
      <span class="advancedAllScoresClass skillPercentileHolder pull-right"><small>Your percentile in class: <span class="skillPercentileLabel"></span>%</small></span>
      </h4>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" data-score="0"><h5>To improve your Online Activity skill, you should:</h5></div>
      <ol class="list-group">
        <li class="list-group-item">1. Re-watch videos you did not completely understand</li>
        <li class="list-group-item">2. Pause videos to take notes or write down questions</li>
        <li class="list-group-item">3. Redo quiz questions for practice</li>
        <li class="list-group-item">4. Visit these online resources to learn about online interaction: <br>
          <ol><li class="list-group-item">
	    <a href="https://www.youtube.com/watch?v=UAhRf3U50lM" target="_blank" data-toggle="tooltip" title="How to Take Great Notes"><?php echo Phalcon\Tag::image("img/videoActivity1.png"); ?></a>
            <a href="http://theconversation.com/whats-the-best-most-effective-way-to-take-notes-41961" target="_blank" data-toggle="tooltip" title="What’s the best, most effective way to take notes?"><?php echo Phalcon\Tag::image("img/textActivity1.png"); ?></a>
          </li></ol>
        </li>
      </ul>
    </div>
  </div>

  <div class="regulationSkillTemplate skillTemplate">
    <div class="skillScoreBar">
      <h4>Self-Regulation
      <span class="skillInfo pull-right" id="regulationSkillInfo" data-toggle="tooltip" title="Self-Regulation is being able to identify what you know and what you don't know so that you can spend your time more effectively on the material that you need to know most."><span class="glyphicon glyphicon-info-sign"></span></span>
      <span class="advancedAllScores pull-right">Your score: <span class="skillScoreLabel"></span>/10</span>
      <span class="advancedAllScoresClass skillPercentileHolder pull-right"><small>Your percentile in class: <span class="skillPercentileLabel"></span>%</small></span>
      </h4>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" data-score="0"><h5>To improve your Self-Regulation skill, you should:</h5></div>
      <ol class="list-group">
        <li class="list-group-item">1. Try coming back to this visualization more often for additional tips on how to succeed.</li>
        <li class="list-group-item">2. Try following some of the visualization suggestions.</li>
        <li class="list-group-item">3. Try going back over videos and quizzes that you feel would be beneficial from previous sections or chapters</li>
        <li class="list-group-item">4. Visit these online resources to learn more about self-regulation: <br>
          <ol><li class="list-group-item">
	    <a href="https://www.youtube.com/watch?v=jTa1vOH6JjA" target="_blank" data-toggle="tooltip" title="Self-Regulated Learning"><?php echo Phalcon\Tag::image("img/videoRegulation1.png"); ?></a>
            <a href="http://www.facultyfocus.com/articles/teaching-and-learning/what-it-means-to-be-a-self-regulated-learner/" target="_blank" data-toggle="tooltip" title="What it Means to be a Self-Regulated Learner" alt="What it Means to be a Self-Regulated Learner"><?php echo Phalcon\Tag::image("img/textRegulation1.png"); ?></a>
          </li></ol>
        </li>
      </ul>
    </div>
  </div>

  <div class="efficacySkillTemplate skillTemplate">
    <div class="skillScoreBar">
      <h4>Self-Efficacy
      <span class="skillInfo pull-right" id="efficacySkillInfo" data-toggle="tooltip" title="Self-efficacy is being confident in and accurately rating whether you know something or not. Students that are more aware of what they know and what they don't tend to do better."><span class="glyphicon glyphicon-info-sign"></span></span>
      <span class="advancedAllScores pull-right">Your score: <span class="skillScoreLabel"></span>/10</span>
      <span class="advancedAllScoresClass skillPercentileHolder pull-right"><small>Your percentile in class: <span class="skillPercentileLabel"></span>%</small></span>
      </h4>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" data-score="0"><h5>To improve your Self-Efficacy skill, you should:</h5></div>
      <ol class="list-group">
        <li class="list-group-item">1. Try rating your confidence levels more accurately on the quiz questions.</li>
        <li class="list-group-item">2. Visit these online resources to learn more about self-efficacy: <br>
          <ol><li class="list-group-item">
	    <a href="https://www.youtube.com/watch?v=OFsBNqmclZM" target="_blank" data-toggle="tooltip" title="Self-Efficacy"><?php echo Phalcon\Tag::image("img/videoEfficacy1.png"); ?></a>
            <a href="http://reflectd.co/2014/01/20/self-efficacy-beliefs/" target="_blank" data-toggle="tooltip" title="Self-Efficacy Beliefs" alt="Self-Efficacy Beliefs"><?php echo Phalcon\Tag::image("img/textEfficacy1.png"); ?></a>
          </li></ol>
        </li>
      </ul>
    </div>
  </div>

  <div class="consistencySkillTemplate skillTemplate">
    <div class="skillScoreBar">
      <h4>Consistency
      <span class="skillInfo pull-right" id="consistencySkillInfo" data-toggle="tooltip" title="Consistency is how frequently you work on your online activities. Consistent study is better than studying for longer amounts of time right before an exam."><span class="glyphicon glyphicon-info-sign"></span></span>
      <span class="advancedAllScores pull-right">Your score: <span class="skillScoreLabel"></span>/10</span>
      <span class="advancedAllScoresClass skillPercentileHolder pull-right"><small>Your percentile in class: <span class="skillPercentileLabel"></span>%</small></span>
      </h4>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" data-score="0"><h5>To improve your Consistency skill, you should:</h5></div>
      <ol class="list-group">
        <li class="list-group-item">1. Try to schedule a time every day to spend time working on this class.</li>
        <li class="list-group-item">2. Visit these online resources to learn about consistent study: <br>
          <ol><li class="list-group-item">
            <a href="http://www.howtostudy.com/manage-your-time/" target="_blank" data-toggle="tooltip" title="Manage Your Time" alt="Manage Your Time"><?php echo Phalcon\Tag::image("img/textConsistency1.png"); ?></a>
          </li></ol>
        </li>
      </ul>
    </div>
  </div>

<?php
echo Phalcon\Tag::javascriptInclude("js/vendor/d3-radar.js");
echo Phalcon\Tag::javascriptInclude("js/student_skills.js");
echo Phalcon\Tag::stylesheetLink("css/student_skills.css");

} else {
	echo "<p class='alert alert-danger'>Not logged in, or there was an LTI error. Try launching this app again.</p>";
}
