<?php

if ($ltiContext->valid) {
	echo "<p class='bg-success'>Logged in via LTI successfully!</p>";
} else {
	echo "<p class='bg-danger'>Not logged in, or there was an LTI error. Try launching this app again.</p>";
}
//echo "<br />";
//echo $this->tag->linkTo("signup", "Link to do something!");
//echo "<br />";
//echo $this->tag->linkTo("ltiinfo", "View LTI session info");
//echo "<br />";
//echo $this->tag->linkTo("logout", "Log out");
