<h2>Class Dashboard</h2>
<?php
if ( $context->valid ) {
?>
<div id="visualizationContainer">
	<table id="resultList" class="table">
	<thead>
		<tr><td>Lecture Number</td><td>Concept</td><td>Mastery Score</td></tr>
	</thead>
	<tbody>
	</tbody>
	</table>

</div>

<?php
echo Phalcon\Tag::javascriptInclude("js/class.js");
echo Phalcon\Tag::javascriptInclude("js/vendor/c3.min.js");
} else {
	echo "<p class='alert alert-danger'>Not logged in, or there was an LTI error. Try launching this app again.</p>";
}
