<h2>Student Inspector Dashboard</h2>
<?php
if ( $context->valid ) {
?>

<table id="studentList" class="table">
<thead>
	<tr><td>Student Name</td><td>Name Length</td><td>Mastery Score</td></tr>
</thead>
<tbody>
</tbody>
</table>

<?php
echo Phalcon\Tag::javascriptInclude("js/student_inspector.js");
} else {
	echo "<p class='alert alert-danger'>Not logged in, or there was an LTI error. Try launching this app again.</p>";
}
