<h2>Student Inspector Dashboard</h2>
<?php
if ( $context->valid ) {
?>

<table id="studentList" class="table">
<thead>
	<tr><td>Student Name</td><td>Mastery Score</td><td>Video Percentage</td><td>Relative Activity</td><td></td></tr>
</thead>
<tbody>
</tbody>
</table>

<?php
	echo Phalcon\Tag::javascriptInclude("js/vendor/jquery-ui-1.9.2.accordion.min.js");
	echo Phalcon\Tag::javascriptInclude("js/vendor/jquery.knob.min.js");
	echo Phalcon\Tag::javascriptInclude("js/vendor/jquery.stickytableheaders.min.js");
	echo Phalcon\Tag::javascriptInclude("js/vendor/jquery.shorten.js");
	echo Phalcon\Tag::javascriptInclude("js/vendor/c3.min.js");

	echo Phalcon\Tag::javascriptInclude("js/student_inspector.js");
} else {
	echo "<p class='alert alert-danger'>Not logged in, or there was an LTI error. Try launching this app again.</p>";
}
