<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<?php echo $this->tag->getTitle(); ?>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
		<link rel="icon" href="/favicon.ico" type="image/x-icon">

	<?php
	echo Phalcon\Tag::stylesheetLink("css/bootstrap.min.css");
	echo Phalcon\Tag::stylesheetLink("css/bootstrap-theme.min.css");
	echo Phalcon\Tag::stylesheetLink("css/main.css");
	?>
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>

        <?php echo Phalcon\Tag::javascriptInclude("js/vendor/modernizr-2.8.3-respond-1.4.2.min.js");
        echo Phalcon\Tag::javascriptInclude("//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js");
        echo Phalcon\Tag::javascriptInclude("js/vendor/bootstrap.min.js");
        echo Phalcon\Tag::javascriptInclude("js/main.js");
	?>
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-70114533-1', 'auto');
		ga('send', 'pageview');
	</script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand">Student Dashboard</span>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
	  <ul class="nav navbar-nav">
	    <li><?php echo Phalcon\Tag::linkTo("dashboard/resources","Resource List"); ?></li>
		<?php
		// Only show links to dashboards if student is part of the research group
		if (isset($_SESSION["group"]) &&  $_SESSION["group"] == "research") { ?>
			<li><?php echo Phalcon\Tag::linkTo("dashboard/scatterplot_recommender","Test Help"); ?></li>
			<li><?php echo Phalcon\Tag::linkTo("dashboard/student_skills","Improve my Learning"); ?></li>
		<?php } ?>
	  </ul>
          <div class="navbar-form navbar-right" id="navbarButtonHolder" role="form">
	    <?php /* if ($this->ltiContext->valid) {
		    echo Phalcon\Tag::linkTo(array("logout", "Sign Out", "class" => "btn btn-danger"));
		    } else {
		    echo Phalcon\Tag::linkTo(array("https://learningsuite.byu.edu/", "Sign In", "class" => "btn btn-success", "local" => false));
			} */
	    ?>
          </div>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
	<br /><br />
        <?php echo $this->getContent(); ?>
      </div>

      <hr>


      <footer>
		<!--<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><?php echo Phalcon\Tag::image("img/license.svg"); ?></a> &nbsp; This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>. &nbsp; &bull; &nbsp; <?php echo Phalcon\Tag::linkTo("info/privacy","Privacy Policy"); ?> -->
		  <p>&copy; <?php echo date("Y"); ?> BYU. All rights reserved.</p>
      </footer>
    </div> <!-- /container -->
    </body>
</html>

