<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<?php echo $this->tag->getTitle(); ?>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

	<?php
	echo Phalcon\Tag::stylesheetLink("css/bootstrap.min.css");
	echo Phalcon\Tag::stylesheetLink("css/bootstrap-theme.min.css");
	echo Phalcon\Tag::stylesheetLink("css/main.css");
	?>
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>

        <?php echo Phalcon\Tag::javascriptInclude("js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"); ?>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	  <?php echo Phalcon\Tag::linkTo(array("","BYU Open Analytics Visualization","class"=>"navbar-brand","style"=>"color:white;")); ?></li>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
	  <ul class="nav navbar-nav">
	    <li><?php echo Phalcon\Tag::linkTo("statements","Statements"); ?></li>
	    <li><?php echo Phalcon\Tag::linkTo("ltiinfo","LTI Session Info"); ?></li>
	  </ul>
          <div class="navbar-form navbar-right" role="form">
	    <?php if ($this->ltiContext->valid) {
		    echo Phalcon\Tag::linkTo(array("logout", "Sign Out", "class" => "btn btn-danger"));
		    } else {
		    echo Phalcon\Tag::linkTo(array("https://learningsuite.byu.edu/", "Sign In", "class" => "btn btn-success", "local" => false));
		    }
	    ?>
          </div>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <!-- Example row of columns -->
      <!--<div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>-->
	<br /><br />
        <?php echo $this->getContent(); ?>
      </div>

      <hr>


      <footer>
        <p>&copy; footer content</p>
      </footer>
    </div> <!-- /container -->
        <?php echo Phalcon\Tag::javascriptInclude("//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js");
        echo Phalcon\Tag::javascriptInclude("js/vendor/bootstrap.min.js");
        echo Phalcon\Tag::javascriptInclude("js/main.js");
	?>
    </body>
</html>

