<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<?php echo $this->tag->getTitle(); ?>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

	<?php
	echo Phalcon\Tag::stylesheetLink("css/bootstrap.min.css");
	echo Phalcon\Tag::stylesheetLink("css/bootstrap-theme.min.css");
	echo Phalcon\Tag::stylesheetLink("css/main.css");
	?>
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>

        <?php echo Phalcon\Tag::javascriptInclude("js/vendor/modernizr-2.8.3-respond-1.4.2.min.js");
        echo Phalcon\Tag::javascriptInclude("//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js");
        echo Phalcon\Tag::javascriptInclude("js/vendor/bootstrap.min.js");
        echo Phalcon\Tag::javascriptInclude("js/main.js");
	?>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	  <?php echo Phalcon\Tag::linkTo(array("",isset($pageTitle) ? $pageTitle : "BYU Open Analytics","class"=>"navbar-brand","style"=>"color:white;")); ?></li>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
	  <ul class="nav navbar-nav">
	    <!--<li><?php echo Phalcon\Tag::linkTo("dashboard","Main Dashboard"); ?></li>
	    <li><?php echo Phalcon\Tag::linkTo("dashboard/content_recommender","Content Recommender"); ?></li>
	    <li><?php echo Phalcon\Tag::linkTo("dashboard/student_skills","Student Skills"); ?></li>
	    <li class="dropdown">
	    	<?php echo Phalcon\Tag::linkTo(array("statements","Dev &#x25BE;", "data-target"=>"#", "data-toggle"=>"dropdown", "id"=>"devDrop")); ?>
		<ul class="dropdown-menu" aria-labelledby="devDrop">
	          <li><?php echo Phalcon\Tag::linkTo("statements","Recent Statements"); ?></li>
	          <li><?php echo Phalcon\Tag::linkTo("ltiinfo","LTI Session Info"); ?></li>
	          <li><?php echo Phalcon\Tag::linkTo(array("consumer.php?app=openassessments&assessment_id=26","LTI Tool Consumer","target"=>"_blank")); ?></li>
	        </ul>
	    </li>-->
	  </ul>
          <div class="navbar-form navbar-right" id="navbarButtonHolder" role="form">
	    <?php /* if ($this->ltiContext->valid) {
		    echo Phalcon\Tag::linkTo(array("logout", "Sign Out", "class" => "btn btn-danger"));
		    } else {
		    echo Phalcon\Tag::linkTo(array("https://learningsuite.byu.edu/", "Sign In", "class" => "btn btn-success", "local" => false));
			} */
	    ?>
          </div>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
	<br /><br />
        <?php echo $this->getContent(); ?>
      </div>

      <hr>


      <footer>
		<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><?php echo Phalcon\Tag::image("img/license.svg"); ?></a> &nbsp; This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
      </footer>
    </div> <!-- /container -->
    </body>
</html>

