<h2>LTI Session Information</h2>
<?php
if ( $context->valid ) {
    echo "<p class='alert alert-success'>Logged in via LTI successfully!</p>";
    print "<pre>\n";
    print "Context Information:\n\n";
    print $context->dump();
    echo $context->message;
    print_r($context->info);
    print "</pre>\n";
} else {
    echo "<p class='alert alert-danger'>Not logged in, or there was an LTI error. Try launching this app again. Could not establish context: ".$context->message."</p>";
}
