<h2>BYU Open Analytics Dashboards Privacy Policy</h2>
<hr>
<p class="lead">
Information contained in this Privacy Policy is ancillary to any Consent Form(s) signed.
</p>

<p>
<strong>Information Collection and Use:</strong> We use cookies on our websites that collect data in order to 1) identify authenticated users so that we can collect and provide research-related student interactions and information, and 2) identify ways to improve our websites by collecting anonymized statistics via Google Analytics. 
</p>

<p>
Google Analytics collects and processes data about visits to our websites. To learn more, visit “How Google uses data when you use our partners' sites or apps”, located at <a target="_blank" href="//www.google.com/policies/privacy/partners/">www.google.com/policies/privacy/partners/</a>. If you wish to opt out out of Google Analytics data collection, visit <a target="_blank" href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a>.
</p>

<p>
<strong>Personal Information:</strong> Personal information (email address and name) accompanies any messages sent through our feedback forms. We may use this information to contact you regarding your inquiry so that we may further improve our websites. We do not share this information with third parties.
</p>

<p>
<strong>Updates:</strong> This Privacy Policy may be amended at any time.
</p>
